version: '1.8.{build}'

configuration: Release
platform: Any CPU
image:
- Ubuntu1804
- Visual Studio 2017

shallow_clone: true

build: off

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017


    install:
    #- cmd: choco install InnoSetup
    - cmd: SET PATH=%PATH%;C:\Program Files (x86)\Inno Setup 5

    before_build:
    - echo before build
    - nuget restore -Verbosity quiet Source/Mosa.sln

    build:
      verbosity: minimal
      parallel: true
      project: Source/Mosa.sln
      publish_nuget: true

    after_build:
    - cmd: ISCC.exe Source/Inno-Setup-Script/Mosa-Installer.iss

    build_script:

    after_test:

    nuget:
      project_feed: true

    test: off

    assembly_info:
      patch: true
      file: AssemblyInfo.*
      assembly_version: "{version}"
      assembly_file_version: "{version}"
      assembly_informational_version: "{version}"

    artifacts:
    - path: 'bin/MOSA Installer/MOSA-Installer.exe'

  -
    matrix:
      only:
        - image: Ubuntu1804

#    install:
#    - sh: docker pull seblon/mosa-docker-integration

    before_build:
    - echo test

    build: off
#      verbosity: minimal
#      parallel: true
#      project: Source/Mosa.sln

    build_script:
#    - sh: echo $APPVEYOR_BUILD_FOLDER; ls -l $APPVEYOR_BUILD_FOLDER; 
#    - sh: echo $PWD; ls -l; ls -l $PWD ; echo blubb; ls -l $PWD/Ressources; ls -l $PWD/Ressources/docker-integration
    - sh: echo UID "$UID"
    - sh: docker run --name MOSA -v $APPVEYOR_BUILD_FOLDER/Ressources/docker-integration/start:/home/mosa/start2 seblon/mosa-docker-integration /bin/bash -c useradd -m -u $UID sudo && su appveyor -- -c 'echo $UID'
