version: '1.8.{build}'

configuration: Release
platform: Any CPU
image:
- Ubuntu1804
#- Visual Studio 2017

shallow_clone: true

install:
#- cmd: choco install InnoSetup
- cmd: SET PATH=%PATH%;C:\Program Files (x86)\Inno Setup 5

before_build:
- sh: sudo apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- sh: echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
- sh: sudo apt update
- sh: sudo apt-get install -y mono-devel
- sh: sudo apt-get install -y qemu-system-x86

- nuget restore -Verbosity quiet Source/Mosa.sln

build:
  verbosity: minimal
  parallel: true
  project: Source/Mosa.sln
  publish_nuget: true

after_build:
- cmd: ISCC.exe Source/Inno-Setup-Script/Mosa-Installer.iss

build_script:

after_test:

nuget:
  project_feed: true

test: off

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
- path: 'bin/MOSA Installer/MOSA-Installer.exe'

