#!/bin/bash

NAME=mosa-debian-integration

docker build . -t mosa/$NAME

docker rm -f $NAME

docker run -it --name $NAME -v ${PWD}/start:/home/mosa/start mosa/$NAME /bin/bash -c /home/mosa/start
#docker run -it --name $NAME -v ${PWD}/start:/home/mosa/start mosa/$NAME /bin/bash


